# Generated by Django 5.2.18 on 2026-10-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0002_userprofile_biometric_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='encrypted_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='epic_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='epic_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
