# Generated by Django 5.2.18 on 2026-10-09 05:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='recorded_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
